version: '3'
services:
  registry:
    container_name: local-docker-registory
    image: registry:2.3.0
    ports: 
      - '5000:5000'
    volumes:
      - ./var:/var/lib/registry

  registry_front:
    container_name: registory-front
    image: konradkleine/docker-registry-frontend:v2
    environment: 
      - ENV_DOCKER_REGISTRY_HOST=192.168.56.114
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports: 
      - '8080:80'
    volumes:
      - ./var:/var/lib/registry