version: '3'
services:
  registry:
    container_name: local-docker-registory
    image: registry:2.3.0
    ports: 
      - '5000:5000'
    volumes:
      - ./var:/var/lib/registry
    networks:
      app-net:
        ipv4_address: 172.20.0.3

  registry_front:
    container_name: registory-front
    image: konradkleine/docker-registry-frontend:v2
    environment: 
      - ENV_DOCKER_REGISTRY_HOST=172.20.0.3
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports: 
      - '8080:80'
    volumes:
      - ./var:/var/lib/registry
    networks:
      app-net:
        ipv4_address: 172.20.0.2

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16